{{- if .Values.config -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-dethrottler.configMapName" . }}
  labels:
    {{- include "kube-dethrottler.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- with .Values.config }}
    pollInterval: {{ .pollInterval | quote }}
    cooldownPeriod: {{ .cooldownPeriod | quote }}
    taintKey: {{ .taintKey | quote }}
    taintEffect: {{ .taintEffect | quote }}
    nodeFilter: {{ .nodeFilter | default "" | quote }}
    leaderElection:
      enabled: {{ .leaderElection.enabled }}
      leaseName: {{ .leaderElection.leaseName | quote }}
      leaseNamespace: {{ .leaderElection.leaseNamespace | quote }}
    thresholds:
      cpu:
        some:
          avg10: {{ .thresholds.cpu.some.avg10 | default 0 }}
          avg60: {{ .thresholds.cpu.some.avg60 | default 0 }}
          avg300: {{ .thresholds.cpu.some.avg300 | default 0 }}
        full:
          avg10: {{ .thresholds.cpu.full.avg10 | default 0 }}
          avg60: {{ .thresholds.cpu.full.avg60 | default 0 }}
          avg300: {{ .thresholds.cpu.full.avg300 | default 0 }}
      memory:
        some:
          avg10: {{ .thresholds.memory.some.avg10 | default 0 }}
          avg60: {{ .thresholds.memory.some.avg60 | default 0 }}
          avg300: {{ .thresholds.memory.some.avg300 | default 0 }}
        full:
          avg10: {{ .thresholds.memory.full.avg10 | default 0 }}
          avg60: {{ .thresholds.memory.full.avg60 | default 0 }}
          avg300: {{ .thresholds.memory.full.avg300 | default 0 }}
      io:
        some:
          avg10: {{ .thresholds.io.some.avg10 | default 0 }}
          avg60: {{ .thresholds.io.some.avg60 | default 0 }}
          avg300: {{ .thresholds.io.some.avg300 | default 0 }}
        full:
          avg10: {{ .thresholds.io.full.avg10 | default 0 }}
          avg60: {{ .thresholds.io.full.avg60 | default 0 }}
          avg300: {{ .thresholds.io.full.avg300 | default 0 }}
    {{- if .kubeconfigPath }}
    kubeconfigPath: {{ .kubeconfigPath | quote }}
    {{- end }}
    {{- end -}}
{{- end -}}
